### ISSUE TITLE
test dependency on TestCase

### ISSUE THREAD

**Issue by AvdN** [pyvideo/steve#45]
For tox / pytest it is not necessary to have the classes in the test/test_*.py files be
dependent on TestCase, but pytest can handle it.

Some new tests are already no longer subclasses of unittest.TestCase (e.g. test_cmdline.VerifyTestCase). 

TestCase suclassing should be removed (my preference) or applied consistently.

**Comment by willkg** [comment]
That's a mistake. They should all subclass `TestCase`. I'll fix that now.

**Comment by willkg** [comment]
Fixed in ea85a90
