### ISSUE TITLE
get_all_categories isn't getting all the categories

### ISSUE THREAD

**Issue by codersquid** [pyvideo/steve#53]
richardapi.get_all_categories seems to be getting a page for me, rather than all of the items. This causes a steve-cmd push to fail even when I've created a new category. calling /category directly shows a count of 71, get_all_categories returns 50. The method is using `limit=0` which I think could be tastypie kruft.

```
In [1]:
import json
import requests
from steve import util as ut
In [2]: cfg = ut.get_project_config()
In [3]: from steve import richardapi as api
In [5]: cats = api.get_all_categories('http://pyvideo.org/api/v2/')
In [8]: len(cats)
Out[8]:
50
In [9]: r = requests.get("http://pyvideo.org/api/v2/category/")
In [10]: r.json().get('count')
Out[10]:
71
```

**Comment by willkg** [comment]
Boo. :(

I'll take a look at it. If we can fix it in steve without updating pyvideo, that'd be swell. If we can't, then I'm not sure what to do offhand in the short term. Maybe screen-scraping.

**Comment by willkg** [comment]
^^^ @codersquid That should fix it. It'll go through the pages of results and get them all now.
